### PR TITLE
Add crown icons

### PR DESCRIPTION
**Pull request by sja**
I added a crown icon with the variants `-plus` and `-minus`.

### CODE REVIEW

**Comment by sja** [comment]
Is there a problem with the crowns? Or was there no time to review my pull request?

**Comment by puzrin** [comment]
Sorry for delay. We are replacing fontforge with [svg2ttf](https://github.com/fontello/svg2ttf) on fontello. Hope to finish tomorrow (some unexpected difficult bugs happened). I'll add your icons on site right after that.

**Comment by puzrin** [comment]
Take a look on demo page http://fontello.github.io/fontelico.font/demo.html . I can add icons as is, but i think, it's possible to improve those. Most comments are about changes for small sizes:
1. Circles can be filled (nobody will see small white sicrles in small size)
2. Crown rays could be more fat at the ends
3. More space needed around minus
4. I don't know your plans, but if you are not going to place crown near crown-plus & crown-minus, i would center crown vertically. Now it will significant shift, when placed standalone
5. Space above crown bottom line could be increased (now looks too blured).

**Comment by sja** [comment]
Ok, thanks for the feedback.
1. I'll fill them.
2. Hmm, I'll try. But I want to have a clear optical separation between the circles and the rays.
3. Aggree.
4. Can you add this hint to the readme? I was looking for a reference base line which becomes the baseline in the font later, too.
5. Ok, I know what you mean. I'll fix this, too.

**Comment by puzrin** [comment]
`2`. No problems. Probably, when you fill circles, that will be not so critical.

`4`. Added some advices

`5`. I mean, check white spaces everywhere - if it takes less than 1 px on display, it will be blured.

I don't have specific grid requirements. But it can be interesting for you to read this acticle https://github.com/blog/1135-the-making-of-octicons , there are comments about making small images sharp enougth.

**Pull request merged**
