### PR TITLE
Crown improvement

### PR DESCRIPTION
**Pull request by sja**
- [x] Circles filled
- [x] Crown rays more fat
- [x] More space added between plus/minus and crown
- [x] Centered crowns vertically.
- [x] White horizontal line (space) of crown increased
- [x] Alignment corrected for small sizes

### CODE REVIEW

**Comment by sja** [comment]
Hmm, just silence around this PR?

**Comment by puzrin** [comment]
Will upate soon. We are testing svg2ttf, and i had to temporary freeze font changes, to have stable test patterns.

Sorry for inconvenience.

**Comment by puzrin** [comment]
Fontello will be updated after we resolve problem with importing fonts into OSX Font Book.

**Comment by puzrin** [comment]
Your crowns are on fontello.com now.

**Comment by sja** [comment]
Great, thanks a lot!

**Pull request merged**
