### PR TITLE
Adding bwsimple icon SVG

### PR DESCRIPTION
**Pull request by ooduor**
for bwsimple logo

### CODE REVIEW

**Comment by puzrin** [comment]
Sorry for late reply. What it this icon about (negative underscored star) ?

**Comment by ooduor** [comment]
No problem. It is the icon for www.blackwhitesimple.com, I have a website 'am using fontello social icons and wanted to download this from my set hence the request. Thank you!

**Comment by puzrin** [comment]
Hm, if it's a brand icon, `brandico` is a better place for it.

But in general, site looks quite specific, i'm not sure that someone else will need it's logo. May be, you can just use it via new "custom icons" feature?

**Comment by ooduor** [comment]
Ah, yes. I didn't know about brandico, and it's more appropriate for my case. Let me fork and add it there. Thanks alot.

**Comment by ooduor** [comment]
How does the customs icons feature work? Like if I want to add a custom icon to a set I have ready for download so that I download them together.

**Comment by puzrin** [comment]
Just drag your SVG image on fontello page, and select it, when in appears in "Custom Icons" section. You no longer depend on built-in collections.

Prior to import - make sure, that all contours are joined into single outline in your editor.

**Comment by ooduor** [comment]
Ok. I realize that, this is a great feature especially for private use. I will need to work on the contours now.

**Pull request closed without merging**
