### PR TITLE
Added Welsh Dragon icon

### PR DESCRIPTION
**Pull request by homotechsual**
New icon - outline of a Welsh Dragon.

### CODE REVIEW

**Comment by puzrin** [comment]
Mikey, this image contain too many small details, and will not be good in small size. I don't think, that it will be good to include in in fontelico.

I'd suggest to wait a bit, until fontello allow to import svg and allow you to be independent from current presets. That should happen quite soon.

**Comment by homotechsual** [comment]
I did check the image at small scale and it looked fine to me but I will seek an alternate project with a more reasonable approach. Thanks for your consideration.

**Comment by puzrin** [comment]
No problems. If you need to pack custom svg into font right now - try icomoon.

**Comment by homotechsual** [comment]
Thanks for the recommendation. Sorry for my bluntness, long day! When is fontello getting the feature do you know?

**Comment by puzrin** [comment]
I think, < 1 month. Since this is non-commercial pet-project, it has different priorities - more code quality, instead of more features.

https://github.com/fontello/fontello/issues/65#issuecomment-21215809

**Comment by homotechsual** [comment]
Thanks :-)

**Pull request closed without merging**
